name: MolGpKa
channels:
  - rdkit
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - jupyter
  - pytorch
  - scikit-learn
  - scikit-learn-intelex
  - numpy
  - pandas
  - rdkit
  - flask
  - uwsgi
  - pip:
    - py3Dmol
    - requests
    - git+https://github.com/pyg-team/pytorch_geometric
    - jupyter-lsp==2.2.2
