apiVersion: v1
kind: Service
metadata:
  name: cts-molgpka-nginx
  namespace: qed-kube-dev
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    app: cts-molgpka-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
      # nodePort: 30002
